package model;
// Generated 2017-5-26 14:17:42 by Hibernate Tools 3.6.0.Final

/**
 * Carts generated by hbm2java
 */
public class Carts implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private CartsId id;
	private Integer number;

	public Carts() {
	}

	public Carts(CartsId id) {
		this.id = id;
	}

	public Carts(CartsId id, Integer number) {
		this.id = id;
		this.number = number;
	}

	public Carts(int uid, int bid, Integer number) {
		CartsId cId = new CartsId(uid, bid);
		this.id = cId;
		this.number = number;
	}

	public CartsId getId() {
		return this.id;
	}

	public void setId(CartsId id) {
		this.id = id;
	}

	public int getUid() {
		return this.id.getUid();
	}

	public void setUid(int uid) {
		this.id.setUid(uid);
	}

	public int getBid() {
		return this.id.getBid();
	}

	public void setBid(int bid) {
		this.id.setBid(bid);
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
