package model;
// Generated 2017-5-26 14:17:42 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer oid;
	private int uid;
	private int total;
	private Date time;
	private String status;
	private Set<Items> items;

	public Orders() {
	}

	public Orders(int uid, int total, Date time) {
		this.uid = uid;
		this.total = total;
		this.time = time;
	}

	public Orders(int uid, int total, Date time, String status) {
		this.uid = uid;
		this.total = total;
		this.time = time;
		this.status = status;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Items> getItems() {
		return this.items;
	}

	public void setItems(Set<Items> items) {
		this.items = items;
	}

}
