 function cate(category){
    	switch (category) {
		case "A":
			return "马列主义毛思邓论";
		case "B":
			return "哲学";
		case "C":
			return "社会科学总论";
		case "D":
			return "政治、法律";
		case "E":
			return "军事";
		case "F":
			return "经济";
		case "G":
			return "文化、科学、教育、体育";
		case "H":
			return "语言、文字";
		case "I":
			return "文学";
		case "J":
			return "艺术";
		case "K":
			return "历史、地理";
		case "N":
			return "自然科学总论";
		case "O":
			return "数理科学和化学";
		case "P":
			return "天文学、地球科学";
		case "Q":
			return "生物科学";
		case "R":
			return "医药、卫生";
		case "S":
			return "农业科学";
		case "T":
			return "工业技术";
		case "U":
			return "交通运输";
		case "V":
			return "航空、航天";
		case "X":
			return "环境科学、安全科学";
		case "Z":
			return "综合性图书";
		default:
			return category;
		}
}
 
function cateInt(num){
	switch (num) {
	case 0:
		return "马列主义毛思邓论";
	case 1:
		return "哲学";
	case 2:
		return "社会科学总论";
	case 3:
		return "政治、法律";
	case 4:
		return "军事";
	case 5:
		return "经济";
	case 6:
		return "文化、科学、教育、体育";
	case 7:
		return "语言、文字";
	case 8:
		return "文学";
	case 9:
		return "艺术";
	case 10:
		return "历史、地理";
	case 11:
		return "自然科学总论";
	case 12:
		return "数理科学和化学";
	case 13:
		return "天文学、地球科学";
	case 14:
		return "生物科学";
	case 15:
		return "医药、卫生";
	case 16:
		return "农业科学";
	case 17:
		return "工业技术";
	case 18:
		return "交通运输";
	case 19:
		return "航空、航天";
	case 20:
		return "环境科学、安全科学";
	case 21:
		return "综合性图书";
	default:
		return category;
	}
}